# Generated by Django 2.1.15 on 2020-01-12 03:13

from django.db import migrations, models
import django.db.models.deletion


def default_car(apps, schema_editor):
    Car = apps.get_model("main", "Car")
    db_alias = schema_editor.connection.alias
    Car.objects.using(db_alias).create(name="Default Car")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(default_car),
        migrations.AddField(
            model_name='laptime',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Car'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='laptime',
            unique_together={('driver', 'track', 'car')},
        ),
    ]
