# Generated by Django 2.1.15 on 2020-01-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_laptime_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptime',
            name='media',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
