# Generated by Django 2.1.15 on 2020-01-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_laptime_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Track')),
            ],
        ),
    ]
